name: Android CI
paths:
- 'Android/**'
- '.github/workflows/android-ci.yml'
push:
branches: [ main ]
paths:
- 'Android/**'
- '.github/workflows/android-ci.yml'


jobs:
build-test-lint:
runs-on: ubuntu-latest
timeout-minutes: 45
permissions:
contents: read
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up JDK 17 (AGP compatible)
uses: actions/setup-java@v4
with:
distribution: 'temurin'
java-version: '17'


- name: Gradle setup & cache
uses: gradle/actions/setup-gradle@v3
with:
build-root-directory: Android


- name: Make gradlew executable
run: chmod +x Android/gradlew


- name: Build Debug APK
working-directory: Android
run: ./gradlew --stacktrace assembleDebug


- name: Run unit tests (debug)
working-directory: Android
run: ./gradlew --stacktrace testDebugUnitTest


- name: Android Lint (debug)
working-directory: Android
run: ./gradlew --stacktrace lintDebug


- name: Upload APK artifact
uses: actions/upload-artifact@v4
with:
name: app-debug-apk
path: |
Android/**/build/outputs/apk/debug/*.apk


- name: Upload Lint report
if: always()
uses: actions/upload-artifact@v4
with:
name: lint-report
path: |
Android/**/build/reports/lint-results-debug.html
Android/**/build/reports/lint-results-debug.xml


- name: Upload Unit Test reports
if: always()
uses: actions/upload-artifact@v4
with:
name: unit-test-reports
path: |
Android/**/build/test-results/testDebugUnitTest/**
Android/**/build/reports/tests/testDebugUnitTest/**
